import DashboardLayout from "@/components/layouts/DashboardLayout"

export const metadata = {
    title: "POS System Client",
    description: "Generated by create next app",
}

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <DashboardLayout>
            {children}
        </DashboardLayout>
    )
}
